### ISSUE TITLE
スタンプラリー画面１２３の名前を変更したい

### ISSUE THREAD

**Issue by 2201111-kishikawa** [Aso2101037/2023Dev3warly#18]
画面設計書におけるスタンプラリー画面の名前がわかりずらいので変更したいです。

**Comment by hayama-dev** [comment]
スタンプラリー①画面→スタンプラリー地方別選択画面
スタンプラリー②画面→スタンプラリー都道府県別選択画面
スタンプラリー③画面→スタンプラリー都道府県別詳細画面
に変更

**Comment by 2201111-kishikawa** [comment]
解決しました。ありがとうございます。
